function seedOfficialDiagnostic_() {
  OFFICIAL_DIAGNOSTIC_.forEach(item => upsert_('DIAGNOSTIC_ITEMS','item_id',item));
  OFFICIAL_SELF_MAP_.forEach(item => upsert_('SELF_MAP_ITEMS','item_id',item));
  return {diagnostic:OFFICIAL_DIAGNOSTIC_.length,selfMap:OFFICIAL_SELF_MAP_.length};
}

function diagnosticItem_(number,domain,title,story,challenge,anchor,evidence){
  return {item_id:'D'+String(number).padStart(2,'0'),source_number:number,domain,prompt:title+'\n\n'+story+'\n\nTantangan: '+challenge,rubric_json:JSON.stringify({anchor,evidence,levels:{0:'Kosong, tidak relevan, atau belum cukup untuk menilai proses berpikir.',1:'Tebakan atau kesan; alasan lemah atau mengulang cerita.',2:'Dugaan masuk akal dan hubungan sederhana; bukti atau konsep masih parsial.',3:'Penjelasan koheren berbasis clue atau konsep; belum lengkap pada alternatif, keterbatasan, atau pengujian.',4:'Menangkap clue utama, membandingkan alternatif, memakai bukti atau konsep, menyadari keterbatasan, dan merancang uji pembeda bila relevan.'}}),max_score:4,active:true,source_status:'OFFICIAL_BOOKLET_V2'};
}

const OFFICIAL_DIAGNOSTIC_ = [
  diagnosticItem_(1,'observe_infer','Lift yang Terlalu Tinggi','Raka tinggal di apartemen. Setiap pulang sekolah ia masuk lift sambil membawa payung kecil, bahkan saat cuaca cerah. Anehnya, payung itu tidak pernah dibawa keluar gedung. Di dalam lift, Raka selalu memegangnya tegak lalu tersenyum ketika lift mulai bergerak.','Menurutmu, untuk apa payung itu sebenarnya digunakan? Petunjuk apa dari cerita yang membuatmu berpikir begitu?','Payung dipakai sebagai alat bantu menjangkau atau menekan tombol lift.','Clue bahwa payung hanya digunakan di lift; fungsi alternatif lebih masuk akal daripada untuk hujan.'),
  diagnosticItem_(5,'observe_infer','Kecambah yang Menang Tinggi','Dua kecambah ditanam bersamaan. Yang disimpan di lemari justru lebih tinggi setelah beberapa hari, sedangkan yang dekat jendela lebih pendek tetapi hijau dan kokoh. Jika hanya melihat tinggi, tanaman lemari tampak menang.','Apakah tanaman yang lebih tinggi pasti lebih sehat? Gunakan petunjuk dalam cerita untuk membela jawabanmu.','Tidak. Kecambah gelap mengalami etiolasi; tinggi bukan satu-satunya indikator sehat.','Menggunakan warna, kekokohan, cahaya atau fotosintesis sebagai bukti.'),
  diagnosticItem_(8,'evidence_experiment','Balapan Dua Mobil Mainan','Dua mobil mainan dilepas dari lintasan miring yang sama. Mobil A lebih berat. Mobil B lebih ringan. A tiba lebih dulu. Seorang siswa langsung menyimpulkan bahwa benda lebih berat selalu lebih cepat.','Apakah kesimpulan itu sudah layak? Sebutkan hal lain yang harus diperiksa sebelum mempercayainya.','Belum layak menyimpulkan massa sebagai penyebab tunggal.','Meminta kontrol lintasan, roda, gesekan, bentuk, titik lepas, atau variabel relevan lain.'),
  diagnosticItem_(9,'evidence_experiment','Tanaman Pilihan Kelas','Kelas 8A ingin mengetahui pupuk terbaik. Kelompok satu memberi kompos pada tomat di dekat jendela. Kelompok dua memberi pupuk kandang pada tomat di sudut kelas yang lebih gelap. Sebulan kemudian hasilnya berbeda.','Mengapa perbandingan ini belum adil? Rancang versi percobaan yang lebih meyakinkan.','Percobaan tidak adil karena cahaya ikut berubah.','Menjadikan pupuk variabel bebas; pertumbuhan terukur; cahaya, air, media, dan umur dikontrol.'),
  diagnosticItem_(24,'evidence_experiment','Kelas Paling Sejuk','Tiga kelas mengaku paling sejuk. Kelas A punya kipas paling banyak, B punya banyak jendela, C berada di bawah pohon. Kamu hanya punya dua termometer dan waktu satu hari.','Rancang pengukuran yang adil untuk menguji klaim mereka. Kapan, di mana, dan berapa kali kamu mengukur?','Pengukuran harus konsisten lintas kelas dan waktu.','Menentukan titik ukur, jam yang sama, pengulangan, rotasi termometer atau kalibrasi, dan kondisi yang dicatat.'),
  diagnosticItem_(3,'model_concept','Bayangan yang Kabur','Naya menyorotkan senter ke dinding. Ketika tangannya dekat dinding, bayangannya tajam. Saat tangannya digeser mendekati senter, bayangan membesar tetapi tepinya makin kabur.','Tanpa menyebut rumus, jelaskan apa yang mungkin terjadi pada perjalanan cahaya.','Ukuran dan ketajaman bayangan berubah karena geometri sumber cahaya, benda, dan layar.','Menjelaskan berkas cahaya, jarak, atau daerah bayangan dan penumbra.'),
  diagnosticItem_(13,'model_concept','Air Panas yang Berhenti Naik','Saat air dipanaskan, suhu naik dari 30, 45, 61, 78, 92 hingga sekitar 100 derajat C. Pemanasan diteruskan, tetapi angka termometer tidak naik banyak sementara air makin banyak berubah menjadi uap.','Ke mana energi pemanasan berikutnya mungkin pergi? Jelaskan dengan bahasamu sendiri.','Energi terutama digunakan untuk perubahan fase menjadi uap, bukan menaikkan suhu secara besar.','Menjelaskan energi perubahan wujud atau energi laten dengan bahasa sendiri.'),
  diagnosticItem_(12,'systems_causality','Tikus yang Mendadak Banyak','Petani di sebuah desa mengurangi jumlah ular karena takut. Beberapa bulan kemudian tikus meningkat dan padi lebih banyak rusak. Namun pada saat yang sama musim hujan juga berubah.','Apakah berkurangnya ular pasti satu-satunya penyebab? Susun penjelasan yang membedakan hubungan sebab-akibat dari kebetulan.','Ular dapat memengaruhi tikus, tetapi musim atau perubahan lain juga mungkin berpengaruh.','Membedakan korelasi dan kausalitas serta meminta data pembanding.'),
  diagnosticItem_(22,'systems_causality','Kolam yang Tiba-tiba Hijau','Kolam sekolah mendadak sangat hijau setelah beberapa minggu. Di dekatnya ada kebun yang baru sering diberi pupuk. Ikan terlihat lebih sering berada dekat permukaan.','Buat dua kemungkinan penjelasan. Data apa yang perlu dikumpulkan agar kamu tidak sekadar menebak?','Kemungkinan ledakan alga atau eutrofikasi dan penurunan oksigen; alternatif lain tetap mungkin.','Meminta data nutrien, oksigen terlarut, pH, suhu, alga, aliran, dan waktu.'),
  diagnosticItem_(10,'technology_design','Lampu Kelas Misterius','Setiap istirahat, lampu kelas tetap menyala walaupun ruangan kosong. Ada tiga usul: memasang tulisan pengingat, menunjuk petugas, atau membuat lampu otomatis yang mati ketika ruangan kosong.','Data apa yang perlu dikumpulkan untuk menentukan solusi mana yang paling efektif, bukan sekadar paling keren?','Kumpulkan konsumsi energi, lama ruang kosong, kepatuhan, biaya, dan efektivitas tiap solusi.','Memilih indikator yang dapat dibandingkan sebelum keputusan.'),
  diagnosticItem_(21,'technology_design','Kotak Pendingin Tanpa Listrik','Kamu harus membawa es selama dua jam tanpa kulkas. Tersedia kardus, aluminium foil, kain, koran, botol plastik, dan selotip. Semua kelompok mendapat jumlah es yang sama.','Pilih bahan dan desainmu. Jelaskan alasan ilmiah mengapa desain itu seharusnya memperlambat es mencair.','Desain harus mengurangi perpindahan panas dari lingkungan ke es.','Memilih isolator, lapisan, atau ruang udara dan menjelaskan konduksi, konveksi, atau radiasi secara relevan.'),
  diagnosticItem_(28,'technology_design','Satu Botol Air untuk Tanaman','Kamu harus membuat alat penyiram tanaman yang dapat bekerja sendiri selama akhir pekan dengan satu botol bekas, tali atau kain, dan benda sederhana di kelas.','Jelaskan rancanganmu, prinsip sains yang dimanfaatkan, dan satu kemungkinan kegagalannya.','Contoh solusi menggunakan sistem sumbu atau kapilaritas maupun tetes gravitasi.','Menjelaskan mekanisme, aliran, kebutuhan tanaman, dan mode kegagalan.')
];

const OFFICIAL_SELF_MAP_ = [
  ['SM01','curiosity','Aku biasanya penasaran ketika menemukan sesuatu yang aneh.'],
  ['SM02','epistemic_humility','Aku nyaman mengatakan belum tahu lalu mencari bukti.'],
  ['SM03','pattern_causality','Aku suka mencari pola atau hubungan sebab-akibat.'],
  ['SM04','making_experiment','Aku menikmati percobaan, membongkar cara kerja benda, atau membuat sesuatu.'],
  ['SM05','evidence_revision','Aku mau mengubah pendapat jika bukti baru lebih kuat.'],
  ['SM06','science_interest','Aku tertarik pada alam, teknologi, angka, atau cara kerja dunia.']
].map(x=>({item_id:x[0],dimension:x[1],prompt:x[2],active:true,source_status:'OFFICIAL_BOOKLET_V2'}));
