const PRACTICE_GUIDE_ = Object.freeze({
  title:'Panduan Praktik Sains Purwaverse',
  intro:'Praktik dilakukan untuk menghasilkan bukti, bukan sekadar mengikuti resep. Alat boleh disesuaikan oleh guru selama tujuan, keselamatan, dan data yang dicari tetap sama.',
  sop:[
    ['Sebelum praktik','Baca misi dan aturan keselamatan. Pastikan guru menyetujui alat, bahan, lokasi, serta pembagian tugas.'],
    ['Kenali risiko','Periksa benda tajam, pecah, panas, listrik, alergi, tumpahan, dan gerak tubuh. Jangan menggunakan bahan atau prosedur yang belum disetujui guru.'],
    ['Siapkan area','Rapikan meja, gunakan pelindung yang diminta, ikat rambut panjang, dan jauhkan makanan atau minuman dari area praktik.'],
    ['Lakukan Trial 1','Ubah satu hal yang diuji, jaga kondisi lain semirip mungkin, lalu catat hasil apa adanya termasuk kegagalan.'],
    ['Periksa dan perbaiki','Bandingkan prediksi dengan data. Temukan sumber kesalahan atau bagian rancangan yang dapat diperbaiki.'],
    ['Lakukan Trial 2','Ulangi dengan satu perbaikan yang jelas dan catat apakah hasil menjadi lebih konsisten atau informatif.'],
    ['Simpulkan dari bukti','Kesimpulan harus merujuk data. Jelaskan juga batas model dan hal yang belum dapat dipastikan.'],
    ['Akhiri dengan aman','Matikan atau kembalikan alat, buang bahan sesuai arahan guru, bersihkan meja, dan cuci tangan.']
  ],
  teamRoles:[
    ['Scientist Leader','Menjaga misi, membagi tugas, dan mengirim laporan tim.'],
    ['Deputy Scientist Leader','Menggantikan leader bila diperlukan dan memeriksa kelengkapan laporan.'],
    ['Lab Operator','Menyiapkan serta menggunakan alat sesuai SOP.'],
    ['Data Recorder','Mencatat data, perubahan, dan kejadian yang tidak terduga.'],
    ['Evidence Checker','Memastikan kesimpulan benar-benar didukung bukti.'],
    ['Communicator','Menyiapkan penjelasan singkat hasil tim.']
  ],
  successExample:{
    title:'Contoh berhasil: denyut dan pemulihan',
    mission:'Menyelidiki perubahan denyut setelah aktivitas ringan dan waktu yang dibutuhkan untuk mendekati kondisi awal.',
    prediction:'Setelah aktivitas, denyut meningkat lalu turun bertahap saat beristirahat.',
    tools:'Stopwatch pinjaman, kursi, lembar data, pensil.',
    trial1:'Denyut istirahat dihitung 30 detik. Satu siswa melakukan jalan di tempat 60 detik. Denyut dihitung segera dan setelah dua menit.',
    data:'Istirahat 38 denyut/30 detik; segera setelah aktivitas 61; setelah 1 menit 48; setelah 2 menit 41.',
    improvement:'Trial 1 terlambat mulai menghitung. Pada Trial 2, pencatat waktu memberi aba-aba dan penghitung sudah siap.',
    trial2:'Istirahat 37; segera 64; setelah 1 menit 49; setelah 2 menit 40 denyut/30 detik.',
    evidence:'Kedua trial menunjukkan kenaikan segera setelah aktivitas dan penurunan selama pemulihan.',
    conclusion:'Aktivitas ringan meningkatkan denyut, kemudian denyut mendekati kondisi awal selama istirahat.',
    modelLimit:'Hasil satu siswa tidak mewakili semua orang; kebugaran, ketepatan hitung, dan intensitas gerak dapat memengaruhi data.',
    reflection:'Pembagian tugas dan aba-aba yang jelas membuat Trial 2 lebih rapi.'
  },
  reportChecklist:['Identitas tim','Prediksi beralasan','Alat yang benar-benar digunakan','Data Trial 1','Perbaikan yang jelas','Data Trial 2','Bukti','Kesimpulan','Batas model','Peran anggota']
});

function practiceDefinition_(activityId,title,mission,context,duration,tools,alternatives,safety,method,dataColumns,success,concepts,evidence,avoid){
  return Object.freeze({activity_id:activityId,title,mission,context,duration,tools,alternatives,safety,method,data_columns:dataColumns,success_criteria:success,practice_link:{concepts,evidence,avoid},prediction_prompt:'Apa yang timmu perkirakan akan terjadi? Jelaskan alasannya berdasarkan materi.',improve_prompt:'Apa satu kelemahan Trial 1 yang paling penting dan perbaikan apa yang dipilih?',evidence_prompt:'Data mana yang paling kuat mendukung atau menolak prediksi?',conclusion_prompt:'Apa kesimpulan yang dapat dibuat berdasarkan data kedua trial?',model_limit_prompt:'Bagian mana dari model atau pengukuran ini yang tidak sama dengan keadaan sebenarnya?',reflection_prompt:'Apa kontribusi setiap anggota dan apa yang akan tim lakukan lebih baik pada praktik berikutnya?'});
}

const PRACTICE_CATALOG_ = Object.freeze([
  practiceDefinition_('CH08-01-U02-LAB01','Jejak Struktur di Dunia Kecil','Bandingkan detail beberapa objek kecil dan gunakan bukti untuk membedakan pengamatan nyata dari model sel.','Struktur kecil pada serat, debu, kertas, atau bagian serangga dapat diamati sesuai kemampuan alat. Gambar sel tercetak dipakai sebagai pembanding konsep, bukan diklaim sebagai hasil mikroskop.',40,['kaca pembesar atau mikroskop yang tersedia','objek aman pilihan guru','kertas dan pensil'],['kamera guru untuk memperbesar hasil','gambar mikroskopis tercetak'],['Jangan menyentuh serangga hidup atau bahan yang tidak dikenal.','Bawa dan gunakan mikroskop sesuai arahan guru.'],['Pilih dua objek aman.','Amati dengan pembesaran yang sama.','Gambar hanya detail yang benar-benar tampak.','Bandingkan dengan gambar model sel dan tandai perbedaannya.'],['Objek/pembesaran','Detail teramati','Detail yang tidak dapat dipastikan'],['Data memisahkan observasi dari dugaan dan tidak mengklaim melihat sel jika alat tidak mendukung.'],['struktur','fungsi','keterbatasan alat'],'gambar dan catatan detail yang konsisten','Menganggap gambar besar selalu lebih tajam atau setiap objek kecil adalah sel.'),
  practiceDefinition_('CH08-01-U03-CHL01','Cell Case File','Identifikasi sel atau jaringan misterius dari kartu bukti struktur dan fungsi.','Ahli biologi menggunakan gabungan ciri, bukan satu petunjuk, untuk membuat identifikasi.',40,['kartu kasus cetak','kartu organel/fungsi','kertas'],['gambar buatan tim'],['Tidak ada bahan biologis; jaga kartu tetap lengkap.'],['Ambil satu kartu kasus.','Susun minimal tiga bukti.','Buat identifikasi awal.','Tukar satu kartu bukti dengan tim lain lalu periksa kembali kesimpulan.'],['Bukti','Makna bukti','Mendukung/tidak mendukung'],['Identifikasi menyebut tingkat keyakinan dan dapat berubah ketika bukti berubah.'],['organel','spesialisasi','organisasi kehidupan'],'rantai alasan dari struktur menuju fungsi','Menentukan jenis sel hanya dari warna atau bentuk umum.'),
  practiceDefinition_('CH08-02-U02-LAB01','Gerbang Penyerapan','Bangun model sederhana untuk menyelidiki pengaruh ukuran partikel terhadap kemampuan melewati penghalang.','Pencernaan memecah makanan dan penyerapan berlangsung melalui permukaan usus; model hanya mewakili sebagian proses tersebut.',80,['dua saringan berbeda','wadah','campuran air dan bahan padat aman yang ditentukan guru'],['kain dan kertas saring','botol bekas yang dipotong guru'],['Tidak mencicipi bahan.','Guru menangani bagian tajam dan menyetujui pembuangan bahan.'],['Siapkan dua penghalang berbeda.','Tuang volume campuran yang sama.','Ukur waktu atau volume yang lolos.','Ubah satu bagian rancangan lalu ulangi.'],['Jenis penghalang','Waktu','Volume lolos','Partikel tertahan'],['Tim dapat menjelaskan bahwa model penyaringan tidak sama dengan kerja enzim dan vili.'],['pencernaan mekanis','penyerapan','vili'],'perbandingan data dua penghalang','Menganggap usus hanya bekerja seperti saringan pasif.'),
  practiceDefinition_('CH08-02-U03-LAB01','Denyut dan Pemulihan','Selidiki perubahan denyut setelah aktivitas ringan dan pola pemulihannya.','Denyut dapat berubah ketika kebutuhan oksigen dan energi sel berubah.',40,['stopwatch pinjaman','kursi','lembar data'],['jam dinding dengan jarum detik','hitungan aba-aba guru'],['Aktivitas harus ringan dan disetujui guru.','Siswa yang tidak nyaman tidak menjadi subjek dan dapat bertugas mencatat.'],['Ukur denyut istirahat.','Lakukan aktivitas ringan dengan durasi tetap.','Ukur segera dan selama pemulihan.','Perbaiki koordinasi pengukuran lalu ulangi.'],['Kondisi/waktu','Denyut per 30 detik','Catatan'],['Dua trial menunjukkan pola dan tim tidak membandingkan kebugaran sebagai ranking.'],['denyut','peredaran','kebutuhan sel'],'pola perubahan dan pemulihan','Menyimpulkan kondisi kesehatan dari satu pengukuran kelas.'),
  practiceDefinition_('CH08-02-U04-LAB01','Paru-Paru Anti Bocor','Rancang model botol dan balon untuk menunjukkan hubungan perubahan volume dengan masuk-keluarnya udara.','Gerak diafragma mengubah volume rongga dada; model botol membantu melihat hubungan mekanis tetapi bukan paru-paru sebenarnya.',80,['botol bekas yang sudah dipotong guru','balon','karet gelang'],['plastik lentur dan selotip'],['Guru menangani pemotongan botol.','Jauhkan balon dari siswa yang memiliki alergi lateks dan sediakan alternatif.'],['Rakit model sesuai diagram guru.','Tarik membran perlahan dan amati balon.','Cari kebocoran pada sambungan.','Perbaiki satu sambungan lalu ulangi.'],['Kondisi membran','Keadaan balon','Ada kebocoran?'],['Model dapat mengembang-mengempis dan tim menjelaskan batas perbandingannya.'],['ventilasi','volume','tekanan udara'],'perubahan balon saat membran digerakkan','Menganggap botol, balon, dan membran sama persis dengan anatomi tubuh.'),
  practiceDefinition_('CH08-02-U05-LAB01','Filter Bukan Ginjal','Uji model penyaringan bertingkat lalu jelaskan mengapa ginjal jauh lebih kompleks.','Ginjal menyaring darah dan mengatur kembali air serta zat terlarut; model hanya menunjukkan pemisahan fisik sederhana.',80,['botol/wadah','kain','kerikil dan pasir bersih','air keruh buatan guru'],['kapas atau kertas saring'],['Air hasil penyaringan tidak boleh diminum.','Guru menangani botol yang dipotong dan pembuangan air.'],['Susun lapisan filter.','Tuang volume air yang sama.','Amati kejernihan dan waktu.','Ubah susunan satu lapisan lalu ulangi.'],['Susunan filter','Waktu','Kejernihan relatif','Catatan'],['Tim memperoleh data pembanding dan menyebut filtrasi model tidak mewakili reabsorpsi nefron.'],['filtrasi','nefron','pengaturan air'],'perubahan kejernihan/waktu setelah perbaikan','Menyatakan ginjal sekadar saringan pasir.'),
  practiceDefinition_('CH08-02-U06-CHL01','Body Systems Rescue','Gunakan kartu gejala dan data untuk menyusun penjelasan hubungan beberapa sistem tanpa membuat diagnosis.','Lelah atau sesak dapat melibatkan pasokan oksigen, zat makanan, peredaran, dan pengeluaran sisa.',40,['kartu kasus dan data','diagram sistem tubuh','kertas panah'],['papan tulis mini'],['Kasus hanya untuk belajar hubungan sistem, bukan mendiagnosis teman.'],['Baca kasus.','Susun alur masukan-angkut-gunakan-keluaran.','Tandai bukti dan bagian yang belum diketahui.','Uji penjelasan dengan kartu data tambahan.'],['Bukti','Sistem terkait','Penjelasan','Ketidakpastian'],['Penjelasan menghubungkan minimal tiga sistem dan menyebut ketidakpastian.'],['antarsistem','homeostasis','bukti'],'diagram sebab-akibat yang konsisten','Menebak penyakit dari satu gejala.'),
  practiceDefinition_('CH08-03-U03-LAB01','Misi Campuran Misterius','Pilih urutan teknik untuk memisahkan campuran aman dengan kehilangan bahan sekecil mungkin.','Campuran dapat dipisahkan berdasarkan ukuran partikel, kelarutan, kemagnetan, atau titik didih.',80,['campuran aman buatan guru','saringan','wadah','sendok'],['magnet berbungkus plastik','kain','penguapan oleh guru bila aman'],['Tidak mencicipi campuran.','Pemanasan hanya dilakukan guru bila dipakai.'],['Identifikasi sifat komponen.','Rancang urutan pemisahan.','Catat jumlah relatif hasil.','Perbaiki urutan untuk mengurangi kehilangan.'],['Tahap','Teknik','Komponen diperoleh','Kehilangan/catatan'],['Urutan teknik dijelaskan dari sifat bahan dan hasil tiap tahap tercatat.'],['campuran','sifat fisika','pemisahan'],'komponen yang berhasil dipisahkan','Memilih teknik hanya karena mudah tanpa menghubungkannya dengan sifat.'),
  practiceDefinition_('CH08-04-U02-LAB01','Bangunan di Meja Gempa','Rancang struktur mini yang bertahan pada pola getaran yang dibuat konsisten.','Getaran tanah dapat memengaruhi bangunan; bentuk, sambungan, alas, dan distribusi massa berpengaruh pada kestabilan model.',80,['karton bekas','sedotan/kertas gulung','selotip','nampan atau karton sebagai meja getar'],['stik es krim','benang'],['Gunakan bahan ringan.','Area uji harus kosong dari benda pecah dan wajah tidak dekat model.'],['Buat kriteria keberhasilan.','Bangun model dengan batas bahan.','Uji dengan pola dorongan yang disepakati.','Perbaiki satu fitur lalu ulangi.'],['Rancangan','Jumlah getaran bertahan','Kerusakan','Catatan'],['Uji dibuat konsisten dan perbaikan dikaitkan dengan bukti Trial 1.'],['getaran','struktur','mitigasi'],'perbandingan ketahanan dua rancangan','Menganggap meja getar sama persis dengan gempa nyata.'),
  practiceDefinition_('CH08-04-U03-CHL01','Jalur Selamat Gunung Api','Rancang jalur evakuasi dari peta bahaya dengan mempertimbangkan beberapa skenario.','Mitigasi memerlukan peta, arah bahaya, kapasitas jalur, titik kumpul, dan komunikasi.',40,['peta skenario cetak','penggaris','pensil warna'],['peta lingkungan sederhana buatan guru'],['Tidak melakukan simulasi lari.','Gunakan data peta sebagai skenario, bukan informasi bencana nyata.'],['Tandai zona dan hambatan.','Pilih rute awal.','Uji dengan kartu perubahan arah bahaya.','Perbaiki rute dan pesan komunikasi.'],['Skenario','Rute','Risiko','Perbaikan'],['Rute memiliki alasan, alternatif, dan tidak bergantung pada simulasi erupsi.'],['bahaya','peta risiko','mitigasi'],'rute yang berubah sesuai skenario','Menganggap satu rute selalu aman untuk semua kondisi.'),
  practiceDefinition_('CH08-05-U01-LAB01','Pindahkan Muatan','Bandingkan usaha ketika gaya atau perpindahan diubah pada pemindahan muatan sederhana.','Usaha mekanis bergantung pada komponen gaya yang searah perpindahan dan jarak perpindahan.',80,['benda bermassa aman','meteran','neraca pegas satu stasiun'],['kantong beras kecil','karet gelang sebagai indikator kualitatif'],['Jangan mengangkat beban berat.','Jalur harus bebas dan neraca pegas digunakan bergiliran.'],['Tentukan lintasan.','Ukur gaya dan jarak pada stasiun alat.','Hitung usaha.','Ubah satu variabel lalu ulangi.'],['Gaya F (N)','Jarak s (m)','Usaha W (J)','Catatan'],['Satuan benar dan perbandingan didasarkan pada hasil ukur, bukan rasa lelah.'],['gaya','perpindahan','usaha'],'hasil pengukuran dan perhitungan','Menyamakan rasa lelah dengan usaha mekanis.'),
  practiceDefinition_('CH08-05-U02-LAB01','Lintasan Energi','Uji pengaruh ketinggian awal terhadap gerak bola pada lintasan sederhana.','Energi potensial berkaitan dengan posisi dan dapat berubah menjadi energi kinetik saat benda bergerak.',80,['bola/kelereng','papan/karton lintasan','penggaris','buku penyangga'],['bola kertas dan talang karton'],['Buat penghalang agar bola tidak mengenai orang atau benda pecah.','Jangan menggunakan benda berat.'],['Tentukan dua ketinggian.','Lepaskan tanpa dorongan.','Ukur jarak atau waktu dengan cara yang sama.','Perbaiki lintasan lalu ulangi.'],['Tinggi awal','Jarak/waktu','Hasil trial','Catatan'],['Tim menghubungkan perubahan hasil dengan tinggi dan mengendalikan cara pelepasan.'],['energi potensial','energi kinetik','perubahan energi'],'pola data pada beberapa tinggi','Menganggap energi hilang seluruhnya ketika benda berhenti.'),
  practiceDefinition_('CH08-05-U03-CHL01','Derek Paling Efektif','Bandingkan waktu untuk mengangkat muatan yang sama menggunakan rancangan derek tangan sederhana.','Daya membandingkan energi atau usaha dengan waktu; efisiensi memperhatikan keluaran berguna terhadap masukan.',80,['benang','gulungan pensil/karton','muatan ringan','penggaris','stopwatch'],['timer pinjaman','hitungan waktu bersama'],['Muatan harus ringan dan tidak diangkat di atas kepala.','Jauhkan jari dari lilitan.'],['Buat derek sederhana.','Angkat muatan pada tinggi tetap.','Catat waktu dan hitung daya relatif.','Perbaiki pegangan atau gulungan lalu ulangi.'],['Muatan','Tinggi','Waktu','Usaha/daya'],['Perbandingan memakai muatan dan tinggi yang sama serta menyebut kehilangan energi.'],['daya','waktu','efisiensi'],'waktu dan usaha pada dua rancangan','Menyebut rancangan tercepat selalu paling efisien tanpa data masukan.'),
  practiceDefinition_('CH08-06-U01-LAB01','Pendulum Penjaga Waktu','Selidiki variabel yang memengaruhi periode ayunan sederhana.','Getaran memiliki periode dan frekuensi; pengujian adil mengubah satu variabel pada satu waktu.',80,['benang','beban ringan','penggaris','stopwatch'],['mur/batu kecil terbungkus','timer bersama'],['Ikat beban dengan kuat.','Ayunkan jauh dari wajah dan batasi sudut kecil.'],['Tentukan variabel yang diubah.','Ukur waktu 10 getaran.','Hitung periode.','Perbaiki cara melepas atau menghitung lalu ulangi.'],['Panjang/massa/sudut','Waktu 10 getaran','Periode','Catatan'],['Minimal dua kondisi dibandingkan dengan variabel kontrol yang disebutkan.'],['getaran','periode','frekuensi'],'waktu beberapa getaran, bukan satu ayunan saja','Mengubah panjang, massa, dan sudut sekaligus.'),
  practiceDefinition_('CH08-06-U02-LAB01','Kode Gelombang Tali','Buat dan ukur pola gelombang pada tali dengan perubahan frekuensi gerak sumber.','Gelombang memindahkan energi melalui gangguan; panjang gelombang dan frekuensi dapat diamati pada model tali.',80,['tali biasa','meteran','penanda lantai'],['benang tebal atau pita panjang'],['Pastikan area bebas dan siswa tidak melilitkan tali pada tubuh.','Gerakkan tali dengan amplitudo kecil.'],['Tandai panjang lintasan.','Buat pola gerak lambat dan cepat.','Catat jumlah gelombang atau jarak puncak.','Perbaiki koordinasi sumber dan pengamat lalu ulangi.'],['Pola gerak','Jumlah gelombang','Jarak puncak','Catatan'],['Pola dibandingkan tanpa mengklaim tali berpindah bersama gelombang.'],['frekuensi','panjang gelombang','energi'],'perubahan pola ketika sumber diubah','Menganggap seluruh tali bergerak menuju ujung.'),
  practiceDefinition_('CH08-06-U03-CHL01','Telepon Gelas Versi 2','Rancang telepon gelas yang mengirim bunyi paling jelas dengan bahan sederhana.','Bunyi berasal dari getaran dan memerlukan medium; tegangan, panjang, dan sambungan memengaruhi model.',80,['dua gelas kertas/plastik','tali','peniti yang digunakan guru'],['kaleng tanpa tepi tajam yang disiapkan guru'],['Guru membuat lubang.','Jangan melilitkan tali pada tubuh dan hindari kaleng tajam.'],['Rakit model awal.','Uji pesan dengan jarak tetap.','Ubah satu variabel seperti tegangan atau panjang.','Ulangi dengan pesan dan penilai yang sama.'],['Rancangan','Jarak','Kejelasan 1-4','Catatan'],['Uji memiliki kriteria kejelasan dan perubahan rancangan didasarkan pada data.'],['getaran','medium','bunyi'],'skor kejelasan pada kondisi berbeda','Menganggap bunyi hanya merambat lurus di sepanjang tali pada semua keadaan.')
].reduce((map,item)=>(map[item.activity_id]=item,map),{}));

function practiceCatalogItem_(activityId){return PRACTICE_CATALOG_[activityId]||null;}
function practiceGuideData_(){return PRACTICE_GUIDE_;}
